### ISSUE TITLE
Run.py cannot work

### ISSUE THREAD

**Issue by tyhmas** [allenjack/GATE#1]
Hi allenjack! I just tried to run your code in the exact way you showed in readme file. But I got error information as following: 

DEBUG:__main__:epoch:0
Traceback (most recent call last):
  File "run.py", line 251, in <module>
    main()
  File "run.py", line 247, in main
    train_model(train_matrix, item_content_matrix, item_relation_matrix, word_seq, test_set, args)
  File "run.py", line 204, in train_model
    batch_x_weight = Variable(torch.from_numpy(batch_x_weight).type(dtype), requires_grad=False)
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: double, float, float16, int64, int32, and uint8.

Thank you for your attention!

**Comment by allenjack** [comment]
Hi,
Thank you for your interests. Could you provide some information about your programming environment?

**Comment by tyhmas** [comment]
Sure. My programming environment is set up as required, specifically with 

python 3.6.5
PyTorch (version: 1.0.1)
numpy (version: 1.16.1)
scipy (version: 1.1.0)
sklearn (version: 0.19.1),

some of them are the latest ones. And my physical machine is running Windows 10 64bit.

**Comment by tyhmas** [comment]
Now I boot up the program again with modifications set as you suggested, it runs! Thank you!

**Comment by allenjack** [comment]
My pleasure!
