### ISSUE TITLE
How to construct test_data's input in prediction

### ISSUE THREAD

**Issue by FayeYGY** [allenjack/GATE#2]
My problem may be too simple, but it confuses me very much. Please pay attention to it~~

In auto encoder, I know, it's trained x to x~, so it can learn more accurate hidden layer. My question is: when  we make predictions, test data is items which users don't rate. So, what's the input? where's input in the network architecture? is gating layer's input? or Encoder_r's input? or other?

Thanks for your attention!

**Comment by allenjack** [comment]
Hi,
The input in the testing phase is the same as the training phase. Basically, we reconstruct the training data in the training phase. And in the test phase, we care more about the prediction scores on the items users do not interact with.

**Comment by FayeYGY** [comment]
Thanks~
Is it means the input in test has many '0'? 
I have two more questions:
(1) Auto encoder is learned for the input being equal to output, if the test input has many '0',  do the predictions have many value approximate to '0'?
(2) If not (1), are you not change the network(parameters and learned weight matrix) at all when in the prediction? just output =  f(test_input).(f is the function learned in the train phrase)
Thanks again!

**Comment by allenjack** [comment]
For (1), the input has a lot of zeros, and most of the outputs have really small values which may approximately equal to zero.
For (2), we do not change the structure and parameters of the network during the test phase.

**Comment by FayeYGY** [comment]
Get it! Thanks~
